// GENERATED BY generate_characters_from_excel.py
import type { Element } from "./types";

export const CHARACTER_DATA: Record<
  string,
  { name: string; element: Element | "None"; iconUrl: string }
> = {
  Aino: {
    name: "Aino",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Aino_Icon.webp",
  },
  Albedo: {
    name: "Albedo",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Albedo_Icon.webp",
  },
  Alhaitham: {
    name: "Alhaitham",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Alhaitham_Icon.webp",
  },
  Aloy: {
    name: "Aloy",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Aloy_Icon.webp",
  },
  Amber: {
    name: "Amber",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Amber_Icon.webp",
  },
  "Arataki Itto": {
    name: "Arataki Itto",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Arataki_Itto_Icon.webp",
  },
  Arlecchino: {
    name: "Arlecchino",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Arlecchino_Icon.webp",
  },
  Baizhu: {
    name: "Baizhu",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Baizhu_Icon.webp",
  },
  Barbara: {
    name: "Barbara",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Barbara_Icon.webp",
  },
  Beidou: {
    name: "Beidou",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Beidou_Icon.webp",
  },
  Bennett: {
    name: "Bennett",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Bennett_Icon.webp",
  },
  Candace: {
    name: "Candace",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Candace_Icon.webp",
  },
  Charlotte: {
    name: "Charlotte",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Charlotte_Icon.webp",
  },
  Chasca: {
    name: "Chasca",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Chasca_Icon.webp",
  },
  Chevreuse: {
    name: "Chevreuse",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Chevreuse_Icon.webp",
  },
  Chiori: {
    name: "Chiori",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Chiori_Icon.webp",
  },
  Chongyun: {
    name: "Chongyun",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Chongyun_Icon.webp",
  },
  Citlali: {
    name: "Citlali",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Citlali_Icon.webp",
  },
  Clorinde: {
    name: "Clorinde",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Clorinde_Icon.webp",
  },
  Collei: {
    name: "Collei",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Collei_Icon.webp",
  },
  Columbina: {
    name: "Columbina",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Columbina_Icon.webp",
  },
  Cyno: {
    name: "Cyno",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Cyno_Icon.webp",
  },
  Dahlia: {
    name: "Dahlia",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Dahlia_Icon.webp",
  },
  Dehya: {
    name: "Dehya",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Dehya_Icon.webp",
  },
  Diluc: {
    name: "Diluc",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Diluc_Icon.webp",
  },
  Diona: {
    name: "Diona",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Diona_Icon.webp",
  },
  Dori: {
    name: "Dori",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Dori_Icon.webp",
  },
  Durin: {
    name: "Durin",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Durin_Icon.webp",
  },
  Emilie: {
    name: "Emilie",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Emilie_Icon.webp",
  },
  Escoffier: {
    name: "Escoffier",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Escoffier_Icon.webp",
  },
  Eula: {
    name: "Eula",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Eula_Icon.webp",
  },
  Faruzan: {
    name: "Faruzan",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Faruzan_Icon.webp",
  },
  Fischl: {
    name: "Fischl",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Fischl_Icon.webp",
  },
  Flins: {
    name: "Flins",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Flins_Icon.webp",
  },
  Freminet: {
    name: "Freminet",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Freminet_Icon.webp",
  },
  Furina: {
    name: "Furina",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Furina_Icon.webp",
  },
  Gaming: {
    name: "Gaming",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Gaming_Icon.webp",
  },
  Ganyu: {
    name: "Ganyu",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Ganyu_Icon.webp",
  },
  Gorou: {
    name: "Gorou",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Gorou_Icon.webp",
  },
  "Hu Tao": {
    name: "Hu Tao",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Hu_Tao_Icon.webp",
  },
  Iansan: {
    name: "Iansan",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Iansan_Icon.webp",
  },
  Ifa: {
    name: "Ifa",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Ifa_Icon.webp",
  },
  Illuga: {
    name: "Illuga",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Illuga_Icon.webp",
  },
  Ineffa: {
    name: "Ineffa",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Ineffa_Icon.webp",
  },
  Jahoda: {
    name: "Jahoda",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Jahoda_Icon.webp",
  },
  Jean: {
    name: "Jean",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Jean_Icon.webp",
  },
  Kachina: {
    name: "Kachina",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Kachina_Icon.webp",
  },
  "Kaedehara Kazuha": {
    name: "Kaedehara Kazuha",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Kaedehara_Kazuha_Icon.webp",
  },
  Kaeya: {
    name: "Kaeya",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Kaeya_Icon.webp",
  },
  "Kamisato Ayaka": {
    name: "Kamisato Ayaka",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Kamisato_Ayaka_Icon.webp",
  },
  "Kamisato Ayato": {
    name: "Kamisato Ayato",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Kamisato_Ayato_Icon.webp",
  },
  Kaveh: {
    name: "Kaveh",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Kaveh_Icon.webp",
  },
  Keqing: {
    name: "Keqing",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Keqing_Icon.webp",
  },
  Kinich: {
    name: "Kinich",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Kinich_Icon.webp",
  },
  Kirara: {
    name: "Kirara",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Kirara_Icon.webp",
  },
  Klee: {
    name: "Klee",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Klee_Icon.webp",
  },
  "Kujou Sara": {
    name: "Kujou Sara",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Kujou_Sara_Icon.webp",
  },
  "Kuki Shinobu": {
    name: "Kuki Shinobu",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Kuki_Shinobu_Icon.webp",
  },
  "Lan Yan": {
    name: "Lan Yan",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Lan_Yan_Icon.webp",
  },
  Lauma: {
    name: "Lauma",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Lauma_Icon.webp",
  },
  Layla: {
    name: "Layla",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Layla_Icon.webp",
  },
  Lisa: {
    name: "Lisa",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Lisa_Icon.webp",
  },
  Lynette: {
    name: "Lynette",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Lynette_Icon.webp",
  },
  Lyney: {
    name: "Lyney",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Lyney_Icon.webp",
  },
  Mavuika: {
    name: "Mavuika",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Mavuika_Icon.webp",
  },
  Mika: {
    name: "Mika",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Mika_Icon.webp",
  },
  Mona: {
    name: "Mona",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Mona_Icon.webp",
  },
  Mualani: {
    name: "Mualani",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Mualani_Icon.webp",
  },
  Nahida: {
    name: "Nahida",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Nahida_Icon.webp",
  },
  Navia: {
    name: "Navia",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Navia_Icon.webp",
  },
  Nefer: {
    name: "Nefer",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Nefer_Icon.webp",
  },
  Neuvillette: {
    name: "Neuvillette",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Neuvillette_Icon.webp",
  },
  Nilou: {
    name: "Nilou",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Nilou_Icon.webp",
  },
  Ningguang: {
    name: "Ningguang",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Ningguang_Icon.webp",
  },
  Noelle: {
    name: "Noelle",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Noelle_Icon.webp",
  },
  Ororon: {
    name: "Ororon",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Ororon_Icon.webp",
  },
  Qiqi: {
    name: "Qiqi",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Qiqi_Icon.webp",
  },
  "Raiden Shogun": {
    name: "Raiden Shogun",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Raiden_Shogun_Icon.webp",
  },
  Razor: {
    name: "Razor",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Razor_Icon.webp",
  },
  Rosaria: {
    name: "Rosaria",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Rosaria_Icon.webp",
  },
  "Sangonomiya Kokomi": {
    name: "Sangonomiya Kokomi",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Sangonomiya_Kokomi_Icon.webp",
  },
  Sayu: {
    name: "Sayu",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Sayu_Icon.webp",
  },
  Sethos: {
    name: "Sethos",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Sethos_Icon.webp",
  },
  Shenhe: {
    name: "Shenhe",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Shenhe_Icon.webp",
  },
  "Shikanoin Heizou": {
    name: "Shikanoin Heizou",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Shikanoin_Heizou_Icon.webp",
  },
  Sigewinne: {
    name: "Sigewinne",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Sigewinne_Icon.webp",
  },
  Skirk: {
    name: "Skirk",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Skirk_Icon.webp",
  },
  Sucrose: {
    name: "Sucrose",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Sucrose_Icon.webp",
  },
  Tartaglia: {
    name: "Tartaglia",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Tartaglia_Icon.webp",
  },
  Thoma: {
    name: "Thoma",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Thoma_Icon.webp",
  },
  Tighnari: {
    name: "Tighnari",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Tighnari_Icon.webp",
  },
  "Anemo Traveler": {
    name: "Traveler",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/AnemoTraveler_Icon.png",
  },
  "Geo Traveler": {
    name: "Traveler",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/GeoTraveler_Icon.png",
  },
  "Electro Traveler": {
    name: "Traveler",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/ElectroTraveler_Icon.png",
  },
  "Dendro Traveler": {
    name: "Traveler",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/DendroTraveler_Icon.png",
  },
  "Hydro Traveler": {
    name: "Traveler",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/HydroTraveler_Icon.png",
  },
  "Pyro Traveler": {
    name: "Traveler",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/PyroTraveler_Icon.png",
  },
  Varesa: {
    name: "Varesa",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Varesa_Icon.webp",
  },
  Venti: {
    name: "Venti",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Venti_Icon.webp",
  },
  Wanderer: {
    name: "Wanderer",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Wanderer_Icon.webp",
  },
  //"Wonderland Manekin": { name: "Wonderland Manekin", element: "None", iconUrl: "/genshinpuzzle/icons/characters/Wonderland Manekin_Icon.webp" },
  Wriothesley: {
    name: "Wriothesley",
    element: "Cryo",
    iconUrl: "/genshinpuzzle/icons/characters/Wriothesley_Icon.webp",
  },
  Xiangling: {
    name: "Xiangling",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Xiangling_Icon.webp",
  },
  Xianyun: {
    name: "Xianyun",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Xianyun_Icon.webp",
  },
  Xiao: {
    name: "Xiao",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Xiao_Icon.webp",
  },
  Xilonen: {
    name: "Xilonen",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Xilonen_Icon.webp",
  },
  Xingqiu: {
    name: "Xingqiu",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Xingqiu_Icon.webp",
  },
  Xinyan: {
    name: "Xinyan",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Xinyan_Icon.webp",
  },
  "Yae Miko": {
    name: "Yae Miko",
    element: "Electro",
    iconUrl: "/genshinpuzzle/icons/characters/Yae_Miko_Icon.webp",
  },
  Yanfei: {
    name: "Yanfei",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Yanfei_Icon.webp",
  },
  Yaoyao: {
    name: "Yaoyao",
    element: "Dendro",
    iconUrl: "/genshinpuzzle/icons/characters/Yaoyao_Icon.webp",
  },
  Yelan: {
    name: "Yelan",
    element: "Hydro",
    iconUrl: "/genshinpuzzle/icons/characters/Yelan_Icon.webp",
  },
  Yoimiya: {
    name: "Yoimiya",
    element: "Pyro",
    iconUrl: "/genshinpuzzle/icons/characters/Yoimiya_Icon.webp",
  },
  "Yumemizuki Mizuki": {
    name: "Yumemizuki Mizuki",
    element: "Anemo",
    iconUrl: "/genshinpuzzle/icons/characters/Yumemizuki_Mizuki_Icon.webp",
  },
  "Yun Jin": {
    name: "Yun Jin",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Yun_Jin_Icon.webp",
  },
  Zhongli: {
    name: "Zhongli",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Zhongli_Icon.webp",
  },
  Zibai: {
    name: "Zibai",
    element: "Geo",
    iconUrl: "/genshinpuzzle/icons/characters/Zibai_Icon.webp",
  },
};

export function getElementForCharacter(name: string): Element | "None" {
  return CHARACTER_DATA[name]?.element ?? "None";
}
