// AUTO-GENERATED. DO NOT EDIT.
// Generated from src/game/characters.ts via scripts/generate_character_elements.ts

export type Element = "Pyro" | "Hydro" | "Electro" | "Cryo" | "Dendro" | "Anemo" | "Geo" | "None";

export const CHARACTER_ELEMENTS: Record<string, Element> = {
  "Aino": "Hydro",
  "Albedo": "Geo",
  "Alhaitham": "Dendro",
  "Aloy": "Cryo",
  "Amber": "Pyro",
  "Arataki Itto": "Geo",
  "Arlecchino": "Pyro",
  "Baizhu": "Dendro",
  "Barbara": "Hydro",
  "Beidou": "Electro",
  "Bennett": "Pyro",
  "Candace": "Hydro",
  "Charlotte": "Cryo",
  "Chasca": "Anemo",
  "Chevreuse": "Pyro",
  "Chiori": "Geo",
  "Chongyun": "Cryo",
  "Citlali": "Cryo",
  "Clorinde": "Electro",
  "Collei": "Dendro",
  "Columbina": "Hydro",
  "Cyno": "Electro",
  "Dahlia": "Hydro",
  "Dehya": "Pyro",
  "Diluc": "Pyro",
  "Diona": "Cryo",
  "Dori": "Electro",
  "Durin": "Pyro",
  "Emilie": "Dendro",
  "Escoffier": "Cryo",
  "Eula": "Cryo",
  "Faruzan": "Anemo",
  "Fischl": "Electro",
  "Flins": "Electro",
  "Freminet": "Cryo",
  "Furina": "Hydro",
  "Gaming": "Pyro",
  "Ganyu": "Cryo",
  "Gorou": "Geo",
  "Hu Tao": "Pyro",
  "Iansan": "Electro",
  "Ifa": "Anemo",
  "Illuga": "Geo",
  "Ineffa": "Electro",
  "Jahoda": "Anemo",
  "Jean": "Anemo",
  "Kachina": "Geo",
  "Kaedehara Kazuha": "Anemo",
  "Kaeya": "Cryo",
  "Kamisato Ayaka": "Cryo",
  "Kamisato Ayato": "Hydro",
  "Kaveh": "Dendro",
  "Keqing": "Electro",
  "Kinich": "Dendro",
  "Kirara": "Dendro",
  "Klee": "Pyro",
  "Kujou Sara": "Electro",
  "Kuki Shinobu": "Electro",
  "Lan Yan": "Anemo",
  "Lauma": "Dendro",
  "Layla": "Cryo",
  "Lisa": "Electro",
  "Lynette": "Anemo",
  "Lyney": "Pyro",
  "Mavuika": "Pyro",
  "Mika": "Cryo",
  "Mona": "Hydro",
  "Mualani": "Hydro",
  "Nahida": "Dendro",
  "Navia": "Geo",
  "Nefer": "Dendro",
  "Neuvillette": "Hydro",
  "Nilou": "Hydro",
  "Ningguang": "Geo",
  "Noelle": "Geo",
  "Ororon": "Electro",
  "Qiqi": "Cryo",
  "Raiden Shogun": "Electro",
  "Razor": "Electro",
  "Rosaria": "Cryo",
  "Sangonomiya Kokomi": "Hydro",
  "Sayu": "Anemo",
  "Sethos": "Electro",
  "Shenhe": "Cryo",
  "Shikanoin Heizou": "Anemo",
  "Sigewinne": "Hydro",
  "Skirk": "Cryo",
  "Sucrose": "Anemo",
  "Tartaglia": "Hydro",
  "Thoma": "Pyro",
  "Tighnari": "Dendro",
  "Anemo Traveler": "Anemo",
  "Geo Traveler": "Geo",
  "Electro Traveler": "Electro",
  "Dendro Traveler": "Dendro",
  "Hydro Traveler": "Hydro",
  "Pyro Traveler": "Pyro",
  "Varesa": "Electro",
  "Venti": "Anemo",
  "Wanderer": "Anemo",
  "Wriothesley": "Cryo",
  "Xiangling": "Pyro",
  "Xianyun": "Anemo",
  "Xiao": "Anemo",
  "Xilonen": "Geo",
  "Xingqiu": "Hydro",
  "Xinyan": "Pyro",
  "Yae Miko": "Electro",
  "Yanfei": "Pyro",
  "Yaoyao": "Dendro",
  "Yelan": "Hydro",
  "Yoimiya": "Pyro",
  "Yumemizuki Mizuki": "Anemo",
  "Yun Jin": "Geo",
  "Zhongli": "Geo",
  "Zibai": "Geo"
};

export function getElementForCharacter(name: string): Element {
  return CHARACTER_ELEMENTS[name] ?? "None";
}
