# GENERATED UTIL: run to rebuild src/game/characters.ts and supabase/functions/_shared/character_elements.ts
# Usage: python scripts/generate_characters_from_excel.py

from __future__ import annotations
from dataclasses import dataclass
from pathlib import Path
from datetime import datetime
import re
import json

from openpyxl import load_workbook

ROOT = Path(__file__).resolve().parents[2]
XLSX = ROOT / "characters.xlsx"

OUT_CHARACTERS = ROOT / "src" / "game" / "characters.ts"
OUT_ELEMENTS = ROOT / "supabase" / "functions" / "_shared" / "character_elements.ts"

ELEMENTS = {"Pyro", "Hydro", "Electro", "Cryo", "Dendro", "Anemo", "Geo"}


@dataclass(frozen=True)
class Row:
  key: str          # object key in TS map
  name: str         # displayed name field
  element: str
  release_iso: str  # YYYY-MM-DD
  icon_path: str


def parse_release_date(v) -> str:
  # Excel cell may be string like "December 23, 2020" or a date object
  if v is None or str(v).strip() == "":
    return "1970-01-01"
  if hasattr(v, "isoformat") and not isinstance(v, str):
    # date/datetime from openpyxl
    try:
      return v.isoformat()[:10]
    except Exception:
      pass
    try:
      return v.date().isoformat()
    except Exception:
      return "1970-01-01"

  s = str(v).strip()
  dt = datetime.strptime(s, "%B %d, %Y")
  return dt.date().isoformat()


def icon_path_for_key(key: str) -> str:
  # Special-case Traveler (Element) icons (they are .png and use ElementTraveler naming)
  m = re.fullmatch(r"Traveler\s*\((Anemo|Geo|Electro|Dendro|Hydro|Pyro)\)", key)
  if m:
    el = m.group(1)
    return f"/icons/characters/{el}Traveler_Icon.png"

  # Default: "Hu Tao" => Hu_Tao_Icon.webp, "Arataki Itto" => Arataki_Itto_Icon.webp
  safe = key.replace(" ", "_")
  return f"/icons/characters/{safe}_Icon.webp"


def ts_key(k: str) -> str:
  # Quote only when needed (spaces, hyphen, etc.)
  if re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", k):
    return k
  return json.dumps(k)


def main() -> None:
  wb = load_workbook(XLSX, data_only=True)
  ws = wb.active

  # Expect headers: name | element | releasedate
  header = [str(c.value).strip().lower() if c.value else "" for c in next(ws.iter_rows(min_row=1, max_row=1))]
  try:
    name_i = header.index("name")
    elem_i = header.index("element")
    date_i = header.index("releasedate")
  except ValueError:
    raise SystemExit(f"Expected headers name/element/releasedate, got: {header}")

  rows: list[Row] = []
  element_map: dict[str, str] = {}

  for r in ws.iter_rows(min_row=2):
    name = (r[name_i].value or "").strip()
    elem = (r[elem_i].value or "").strip()
    rel = parse_release_date(r[date_i].value)

    if not name:
      continue

    if name.strip().lower() == "wonderland manekin":
      continue

    # Exclude base Traveler row; keep Traveler (Element) rows
    if name.strip().lower() == "traveler":
      continue

    if elem not in ELEMENTS:
      elem = "None"

    rows.append(Row(
      key=name,
      name=name,
      element=elem,
      release_iso=rel,
      icon_path=icon_path_for_key(name),
    ))

    if elem != "None":
      element_map[name] = elem

  rows.sort(key=lambda x: x.key.lower())

  # ---- Build src/game/characters.ts ----
  lines: list[str] = []
  lines.append("// GENERATED BY scripts/generate_characters_from_excel.py")
  lines.append('import type { Element } from "./types";')
  lines.append("")
  lines.append("export function asset(path: string) {")
  lines.append('  const clean = path.startsWith("/") ? path.slice(1) : path;')
  lines.append("  return `${import.meta.env.BASE_URL}${clean}`;")
  lines.append("}")
  lines.append("")
  lines.append("export const CHARACTER_DATA: Record<")
  lines.append("  string,")
  lines.append('  { name: string; element: Element | "None"; iconUrl: string; releaseDate: string }')
  lines.append("> = {")

  for row in rows:
    lines.append(f"  {ts_key(row.key)}: {{")
    lines.append(f'    name: {json.dumps(row.name)},')
    lines.append(f'    element: {json.dumps(row.element)},')
    lines.append(f"    iconUrl: asset({json.dumps(row.icon_path)}),")
    lines.append(f"    releaseDate: {json.dumps(row.release_iso)},")
    lines.append("  },")

  lines.append("};")
  lines.append("")
  lines.append('export function getElementForCharacter(name: string): Element | "None" {')
  lines.append('  return CHARACTER_DATA[name]?.element ?? "None";')
  lines.append("}")
  lines.append("")

  OUT_CHARACTERS.parent.mkdir(parents=True, exist_ok=True)
  OUT_CHARACTERS.write_text("\n".join(lines), encoding="utf-8")

  # ---- Build supabase/functions/_shared/character_elements.ts ----
  element_union = '"Pyro" | "Hydro" | "Electro" | "Cryo" | "Dendro" | "Anemo" | "Geo" | "None"'
  out2: list[str] = []
  out2.append("// AUTO-GENERATED. DO NOT EDIT.")
  out2.append("// Generated from characters.xlsx via scripts/generate_characters_from_excel.py")
  out2.append("")
  out2.append(f"export type Element = {element_union};")
  out2.append("")
  out2.append(f"export const CHARACTER_ELEMENTS: Record<string, Element> = {json.dumps(element_map, indent=2)};")
  out2.append("")
  out2.append("export function getElementForCharacter(name: string): Element {")
  out2.append('  return CHARACTER_ELEMENTS[name] ?? "None";')
  out2.append("}")
  out2.append("")

  OUT_ELEMENTS.parent.mkdir(parents=True, exist_ok=True)
  OUT_ELEMENTS.write_text("\n".join(out2), encoding="utf-8")

  print(f"Wrote {OUT_CHARACTERS}")
  print(f"Wrote {OUT_ELEMENTS} ({len(element_map)} entries)")


if __name__ == "__main__":
  main()
